### Product Classification

In [27]:
import pandas as pd
import numpy as np
from pathlib import Path
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer



### Data Loading & Preprocessing


In [30]:
# 1. Define the base directory
BASE_DIR = Path(os.getcwd()).parent

# 2.path folder
DATA_DIR = BASE_DIR / "data"

#3. Join the directory with filename
file_path=DATA_DIR/"Womens Clothing E-Commerce Reviews.csv"
df = pd.read_csv(file_path)
    

## Preprocess

In [16]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
data_loader() # data loading


In [13]:
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses


### 2. Impute/clean

In [28]:
def pre_process(df):
    df['full_text']= df['Title'].fillna('') + " " + df['Review Text'].fillna('')
    return df
df = pre_process(df)

# train-test split

X = df['full_text']
Y= df['Rating']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Build pipeline
model_pipeline=Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('lr', LogisticRegression(max_iter=1000))
])
# Train the model
model_pipeline.fit(X_train, Y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(stop_words='english')),
                ('lr', LogisticRegression(max_iter=1000))])

In [29]:
y_pred=model_pipeline.predict(X_test)
print(classification_report(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       0.45      0.16      0.24       153
           2       0.41      0.21      0.28       317
           3       0.44      0.36      0.39       620
           4       0.45      0.31      0.37      1017
           5       0.73      0.93      0.82      2591

    accuracy                           0.65      4698
   macro avg       0.50      0.40      0.42      4698
weighted avg       0.60      0.65      0.61      4698

[[  25   29   53   13   33]
 [  16   68  116   50   67]
 [  13   54  221  160  172]
 [   0    9   91  317  600]
 [   1    5   18  159 2408]]


In [31]:
import joblib

model_dir=BASE_DIR / "models"
model_dir.mkdir(exist_ok=True)

joblib.dump(model_pipeline, model_dir / "logistic_regression_model.pkl")



['/Users/deepaksivas/Documents/GitHub/ecommerce-ai-nlp-suite/Project1-Ecommerce Clothing Review Classification/models/logistic_regression_model.pkl']